// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebPromotion.Models;

public partial class Agreement
{
    public int AgreementId { get; set; }

    public int DealerCarId { get; set; }

    public int CustomerId { get; set; }

    public int SalesPersonId { get; set; }

    public int LoiId { get; set; }

    public string MethodPayment { get; set; }

    public decimal? BookingFee { get; set; }

    public DateTime AgreementDate { get; set; }

    public virtual ICollection<AgreementUnit> AgreementUnits { get; set; } = new List<AgreementUnit>();

    public virtual CreditApplication CreditApplication { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual DealerCar DealerCar { get; set; }

    public virtual LetterOfIntent Loi { get; set; }

    public virtual Purchase Purchase { get; set; }

    public virtual SalesPerson SalesPerson { get; set; }
}