// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebPromotion.Models;

public partial class Car
{
    public int CarId { get; set; }

    public string Make { get; set; }

    public string CarModel { get; set; }

    public string CarType { get; set; }

    public int? Year { get; set; }

    public string EngineSize { get; set; }

    public string FuelType { get; set; }

    public string Transmission { get; set; }

    public string Color { get; set; }

    public decimal BasePrice { get; set; }

    public string Description { get; set; }

    public virtual ICollection<DealerCar> DealerCars { get; set; } = new List<DealerCar>();

    public virtual ICollection<TesDrive> TesDrives { get; set; } = new List<TesDrive>();
}