// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebPromotion.Models;

public partial class CreditApplication
{
    public int CreditAppId { get; set; }

    public int? AgreementId { get; set; }

    public int? TimePeriod { get; set; }

    public int? PaymentMade { get; set; }

    public double? InterestRate { get; set; }

    public int? InstallmentPerMonth { get; set; }

    public string ApprovalStatus { get; set; }

    public DateTime? ApprovalDate { get; set; }

    public virtual Agreement Agreement { get; set; }

    public virtual ICollection<DocumentCreditApplication> DocumentCreditApplications { get; set; } = new List<DocumentCreditApplication>();
}