// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebPromotion.Models;

public partial class CustomerRating
{
    public int RatingId { get; set; }

    public int CustomerId { get; set; }

    public int? SalesPersonId { get; set; }

    public int? DealerId { get; set; }

    public int? ConsultHistoryId { get; set; }

    public int? TestDriveId { get; set; }

    public string RatingType { get; set; }

    public int RatingValue { get; set; }

    public string Comments { get; set; }

    public DateTime RatingDate { get; set; }

    public virtual ConsultHistory ConsultHistory { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Dealer Dealer { get; set; }

    public virtual SalesPerson SalesPerson { get; set; }

    public virtual TesDrive TestDrive { get; set; }
}