// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebPromotion.Models;

public partial class DealerCarUnit
{
    public int DealerCarUnitId { get; set; }

    public int DealerCarId { get; set; }

    public string Vin { get; set; }

    public string Color { get; set; }

    public int? YearManufacture { get; set; }

    public string Status { get; set; }

    public DateTime AddedDate { get; set; }

    public virtual ICollection<AgreementUnit> AgreementUnits { get; set; } = new List<AgreementUnit>();

    public virtual ICollection<ConsultHistory> ConsultHistories { get; set; } = new List<ConsultHistory>();

    public virtual DealerCar DealerCar { get; set; }

    public virtual ICollection<LoiCarFromDealer> LoiCarFromDealers { get; set; } = new List<LoiCarFromDealer>();

    public virtual ICollection<TestDrive> TestDrives { get; set; } = new List<TestDrive>();
}