// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebPromotion.Models;

public partial class Dealer
{
    public int DealerId { get; set; }

    public string DealerName { get; set; }

    public string Location { get; set; }

    public string Province { get; set; }

    public string City { get; set; }

    public string Address { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<ConsultHistory> ConsultHistories { get; set; } = new List<ConsultHistory>();

    public virtual ICollection<CustomerRating> CustomerRatings { get; set; } = new List<CustomerRating>();

    public virtual ICollection<DealerCar> DealerCars { get; set; } = new List<DealerCar>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<SalesActivityLog> SalesActivityLogs { get; set; } = new List<SalesActivityLog>();

    public virtual ICollection<SalesPerson> SalesPeople { get; set; } = new List<SalesPerson>();

    public virtual ICollection<TesDrive> TesDrives { get; set; } = new List<TesDrive>();
}