// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebPromotion.Models;

public partial class LoiCarFromDealer
{
    public int LoiId { get; set; }

    public int DealerCarUnitId { get; set; }

    public int TotalUnit { get; set; }

    public virtual DealerCarUnit DealerCarUnit { get; set; }

    public virtual LetterOfIntent Loi { get; set; }
}