// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebPromotion.Models;

public partial class Notification
{
    public int NotificationId { get; set; }

    public int? CustomerId { get; set; }

    public int? DealerId { get; set; }

    public int? SalesPersonId { get; set; }

    public int? ConsultHistoryId { get; set; }

    public int? TestDriveId { get; set; }

    public string NotificationType { get; set; }

    public string Message { get; set; }

    public bool IsRead { get; set; }

    public int Priority { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ConsultHistory ConsultHistory { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Dealer Dealer { get; set; }

    public virtual ICollection<SalesActivityLog> SalesActivityLogs { get; set; } = new List<SalesActivityLog>();

    public virtual SalesPerson SalesPerson { get; set; }

    public virtual TesDrive TestDrive { get; set; }
}