// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebPromotion.Models;

public partial class Purchase
{
    public int PurchaseId { get; set; }

    public int CustomerId { get; set; }

    public decimal Nominal { get; set; }

    public int AgreementId { get; set; }

    public string PaymentStatus { get; set; }

    public DateTime? SubmissionDate { get; set; }

    public virtual Agreement Agreement { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<PaymentHistory> PaymentHistories { get; set; } = new List<PaymentHistory>();
}