// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebPromotion.Models;

public partial class SalesActivityLog
{
    public int ActivityLogId { get; set; }

    public int CustomerId { get; set; }

    public int DealerId { get; set; }

    public int SalesPersonId { get; set; }

    public string ActivityType { get; set; }

    public int? RelatedNotificationId { get; set; }

    public DateTime ActivityDate { get; set; }

    public string Details { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Dealer Dealer { get; set; }

    public virtual Notification RelatedNotification { get; set; }

    public virtual SalesPerson SalesPerson { get; set; }
}