// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebPromotion.Models;

public partial class SalesPersonPerformance
{
    public int PerformanceId { get; set; }

    public int SalesPersonId { get; set; }

    public string MetricType { get; set; }

    public double MetricValue { get; set; }

    public DateOnly MetricDate { get; set; }

    public string Notes { get; set; }

    public virtual SalesPerson SalesPerson { get; set; }
}