// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebPromotion.Models;

public partial class WarrantyRegistration
{
    public int WarrantyId { get; set; }

    public int DealerCarId { get; set; }

    public DateTime PurchaseDate { get; set; }

    public int WarrantyPeriod { get; set; }

    public virtual DealerCar DealerCar { get; set; }

    public virtual ICollection<WarrantyClaim> WarrantyClaims { get; set; } = new List<WarrantyClaim>();
}