// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DealerApi.Entities.Models;

public partial class AgreementUnit
{
    public int AgreementUnitId { get; set; }

    public int AgreementId { get; set; }

    public int DealerCarUnitId { get; set; }

    public virtual Agreement Agreement { get; set; }

    public virtual DealerCarUnit DealerCarUnit { get; set; }
}