// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DealerApi.Entities.Models;

public partial class ConsultHistory
{
    public int ConsultHistoryId { get; set; }

    public int? CustomerId { get; set; }

    public int DealerCarUnitId { get; set; }

    public int? SalesPersonId { get; set; }

    public decimal? Budget { get; set; }

    public DateTime ConsultDate { get; set; }

    public string Note { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<CustomerRating> CustomerRatings { get; set; } = new List<CustomerRating>();

    public virtual DealerCarUnit DealerCarUnit { get; set; }

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual SalesPerson SalesPerson { get; set; }
}