// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DealerApi.Entities.Models;

public partial class DealerCar
{
    public int DealerCarId { get; set; }

    public int DealerId { get; set; }

    public int CarId { get; set; }

    public int Stock { get; set; }

    public decimal DealerPrice { get; set; }

    public double? Tax { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Agreement> Agreements { get; set; } = new List<Agreement>();

    public virtual Car Car { get; set; }

    public virtual Dealer Dealer { get; set; }

    public virtual ICollection<DealerCarUnit> DealerCarUnits { get; set; } = new List<DealerCarUnit>();

    public virtual ICollection<LoiCarFromDealer> LoiCarFromDealers { get; set; } = new List<LoiCarFromDealer>();

    public virtual WarrantyRegistration WarrantyRegistration { get; set; }
}