// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DealerApi.Entities.Models;

public partial class DocumentCreditApplication
{
    public int DocumentId { get; set; }

    public int CreditAppId { get; set; }

    public string DocType { get; set; }

    public string FilePath { get; set; }

    public DateOnly? Date { get; set; }

    public virtual CreditApplication CreditApp { get; set; }
}