// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DealerApi.Entities.Models;

public partial class LetterOfIntent
{
    public int LoiId { get; set; }

    public decimal FixPrice { get; set; }

    public double? Discount { get; set; }

    public decimal? DownPayment { get; set; }

    public string Description { get; set; }

    public virtual Agreement Agreement { get; set; }

    public virtual ICollection<LoiCarFromDealer> LoiCarFromDealers { get; set; } = new List<LoiCarFromDealer>();
}