// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DealerApi.Entities.Models;

public partial class PaymentHistory
{
    public int PaymentHistoryId { get; set; }

    public int PurchaseId { get; set; }

    public int PaymentNominal { get; set; }

    public string PaymentType { get; set; }

    public DateTime PaymentDate { get; set; }

    public virtual Purchase Purchase { get; set; }
}