// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DealerApi.Entities.Models;

public partial class SalesPerson
{
    public int SalesPersonId { get; set; }

    public int DealerId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public int? Bonus { get; set; }

    public bool IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Agreement> Agreements { get; set; } = new List<Agreement>();

    public virtual ICollection<ConsultHistory> ConsultHistories { get; set; } = new List<ConsultHistory>();

    public virtual ICollection<CustomerRating> CustomerRatings { get; set; } = new List<CustomerRating>();

    public virtual Dealer Dealer { get; set; }

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<SalesActivityLog> SalesActivityLogs { get; set; } = new List<SalesActivityLog>();

    public virtual ICollection<SalesPersonPerformance> SalesPersonPerformances { get; set; } = new List<SalesPersonPerformance>();

    public virtual ICollection<TestDrive> TestDrives { get; set; } = new List<TestDrive>();
}