// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DealerApi.Entities.Models;

public partial class WarrantyClaim
{
    public int ClaimId { get; set; }

    public int WarrantyId { get; set; }

    public int CustomerId { get; set; }

    public string ClaimStatus { get; set; }

    public int CostCovered { get; set; }

    public string Description { get; set; }

    public DateTime ClaimDate { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual WarrantyRegistration Warranty { get; set; }
}